### ISSUE TITLE
hashbrown build failed

### ISSUE THREAD

**Issue by xiaoyuxlu** [jyao1/rust-uefi-std-stub#4]
hashbrown
0.9.1 works fine.
0.11.2 compile failed. 

[https://github.com/rust-lang/hashbrown/compare/v0.9.1...v0.11.2](https://github.com/rust-lang/hashbrown/compare/v0.9.1...v0.11.2#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R16)

maybe ahash cause build failed on x86_64-unknown-uefi target.
see:
[https://github.com/tkaitchuck/aHash/compare/a05f8bbf6e4d1ae21dd849b213fd1738d50ac71c...06dac67441ed1fe1cb101a75cf91ea61c0638a29](https://github.com/tkaitchuck/aHash/compare/a05f8bbf6e4d1ae21dd849b213fd1738d50ac71c...06dac67441ed1fe1cb101a75cf91ea61c0638a29#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R78)

**Comment by jyao1** [comment]
Please file issue and P-R for ahash to support uefi target.

**Comment by xiaoyuxlu** [comment]
I tested ahash separately, but no problems were found with x86_64-unknown-uefi target

Update hashbrown failed is cause by cargo resolver 1. this resolver will unifying feature of crate.
Use cargo resolver 2 can avoid cargo unifying crate features.

https://github.com/jyao1/rust-td/issues/8
